# Generated by Django 4.1 on 2023-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
                ('soln', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
                ('soln', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
                ('soln', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Question4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
                ('soln', models.CharField(max_length=217)),
            ],
        ),
    ]
