# Generated by Django 4.1.5 on 2023-03-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rquestion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Rquestion2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Rquestion3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Rquestion4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=217)),
            ],
        ),
        migrations.CreateModel(
            name='Option4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeTest.rquestion4')),
            ],
        ),
        migrations.CreateModel(
            name='Option3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeTest.rquestion3')),
            ],
        ),
        migrations.CreateModel(
            name='Option2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeTest.rquestion2')),
            ],
        ),
        migrations.CreateModel(
            name='Option1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeTest.rquestion1')),
            ],
        ),
    ]
