# Generated by Django 4.1.5 on 2023-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeTest', '0002_rquestion1_rquestion2_rquestion3_rquestion4_option4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option1',
            name='op',
            field=models.CharField(max_length=217),
        ),
        migrations.AlterField(
            model_name='option2',
            name='op',
            field=models.CharField(max_length=217),
        ),
        migrations.AlterField(
            model_name='option3',
            name='op',
            field=models.CharField(max_length=217),
        ),
        migrations.AlterField(
            model_name='option4',
            name='op',
            field=models.CharField(max_length=217),
        ),
    ]
